# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170829_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
